apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: cloud-burst-controller
    app.kubernetes.io/managed-by: kustomize
  name: cloud-burst-controller
  namespace: cloud-burst-system
